"""initial_schema

Revision ID: b373651be828
Revises: 
Create Date: 2026-04-02 02:04:15.806512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b373651be828'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attempt_student_session', 'attendance_attempts', ['student_id', 'session_id'])
    op.add_column('attendance_sessions', sa.Column('qr_token_issued_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint('uq_enrollment_student_course', 'enrollments', ['student_id', 'course_id'])
    op.create_unique_constraint('uq_final_student_session', 'final_attendance_records', ['student_id', 'session_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_final_student_session', 'final_attendance_records', type_='unique')
    op.drop_constraint('uq_enrollment_student_course', 'enrollments', type_='unique')
    op.drop_column('attendance_sessions', 'qr_token_issued_at')
    op.drop_constraint('uq_attempt_student_session', 'attendance_attempts', type_='unique')
    # ### end Alembic commands ###
